service: bytemind-scraper

provider:
  name: cloudflare
  stage: prod
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}

plugins:
  - serverless-cloudflare-workers

functions:
  bytemind-scraper:
    name: ${self:service}
    script: index
    events:
      - http: true
